# cleanup
rm -rf obj_dir
rm -f pipelined_top.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace pipelined_top.sv --exe tb_vb_reference.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vpipelined_top.mk Vpipelined_top

# run executable simulation file
obj_dir/Vpipelined_top