# cleanup
rm -rf obj_dir
rm -f fullcpu.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace fullcpu.sv --exe tb_vb_reference.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vfullcpu.mk Vfullcpu

# run executable simulation file
obj_dir/Vfullcpu